
module.MESSAGE_CREATED = 'MESSAGE_CREATED';

module.IS_USER_ONLINE = 'IS_USER_ONLINE';

module.NEW_CONVERSATION = 'NEW_CONVERSATION';

module.NOTIFICATION_CREATED_OR_DELETED = 'NOTIFICATION_CREATED_OR_DELETED';