
exports.MESSAGE_CREATED = 'MESSAGE_CREATED';

exports.IS_USER_ONLINE = 'IS_USER_ONLINE';

exports.NEW_CONVERSATION = 'NEW_CONVERSATION';

exports.NOTIFICATION_CREATED_OR_DELETED = 'NOTIFICATION_CREATED_OR_DELETED';